In [2]:
!pip install numpy

In [7]:
# !pip list
!pip --version

pip 20.2.2 from D:\Python\anaconda3\lib\site-packages\pip (python 3.8)



In [2]:
import numpy as np

In [35]:
def array_numpy():
    a = np.array([
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ])
    print(a)
    print(a[-1][-1])
    "Type data of array"
    print("Type Data :", a.dtype)
    "Shape of array"
    print("Shape :", a.shape)
    "Dimensi of array"
    print("Dimensi :", a.ndim)
array_numpy()

[[1 2 3 4]
 [5 6 7 8]]
8
Type Data : int32
Shape : (2, 4)
Dimensi : 2


In [42]:
def array_of_zeros():
    print(np.array(10))
    print("!--!")
    print(np.zeros(10))
array_of_zeros()

10
!--!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
def array_of_ones():
    print(np.ones(10))
array_of_ones()

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
def array_of_empty():
    print(np.empty((100, 100)))
array_of_empty()

[[7.42972961e-312 7.42973729e-312 3.49012913e-319 ... 5.30973833e+180
  6.23102918e+228 6.02669591e+175]
 [1.77942356e+248 9.08366791e+223 1.07031539e-013 ... 2.18953536e+068
  3.03426193e-086 1.81786144e+185]
 [6.68159286e+151 9.47212685e-154 2.16401696e-027 ... 2.54723493e+151
  1.97641705e+166 3.18489929e-114]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]


In [17]:
def array_of_arange():
    "start,stop,stop"
    print(np.arange(20, 100, 2))
array_of_arange()

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [87]:
def array_of_array():
    arr_1 = np.array([["Ahmad", "Verry", "Setiawan"]])
    arr_2 = np.array([[17, 11, 94]])
    print(arr_1)
    "Append"
    print(arr_1.shape, arr_2.shape)
    print(np.append(arr_1, 17))
    print(np.append(arr_1, arr_2, axis=0))
array_of_array()

[['Ahmad' 'Verry' 'Setiawan']]
(1, 3) (1, 3)
['Ahmad' 'Verry' 'Setiawan' '17']
[['Ahmad' 'Verry' 'Setiawan']
 ['17' '11' '94']]


In [85]:
def array_of_delete():
    arr_1 = np.array(["Ahmad", "Verry", "Setiawan"])
    arr_2 = np.array([17, 11, 94])
    "Delete"
    array_append = np.append(arr_1, arr_2, axis=0)
    print(array_append)
    print("----------")
    print(np.delete(array_append, 0, axis=0))
array_of_delete()

['Ahmad' 'Verry' 'Setiawan' '17' '11' '94']
----------
['Verry' 'Setiawan' '17' '11' '94']


In [116]:
arr1 = np.array([[
    [10,98,54],
    [76,2,46],
    [24,36,92]
],[
    [45,63,82],
    [11,2,57],
    [54,19,45]
]])
arr2 = np.array([[
    [1,2,3],
    [76,2,46],
    [43,92,92]
]])
print(arr1.shape)
print('!----!')
print(arr1[(arr1 >= 82) & (arr1 > 92)])
print('!----!')
print(np.concatenate((arr1, arr2)))
print('!----!')
print(arr1.sum())
print('!----!')
print(arr1.std())

(2, 3, 3)
!----!
[98]
!----!
[[[10 98 54]
  [76  2 46]
  [24 36 92]]

 [[45 63 82]
  [11  2 57]
  [54 19 45]]

 [[ 1  2  3]
  [76  2 46]
  [43 92 92]]]
!----!
816
!----!
29.11089906623367


In [32]:
pre_test_1 = np.arange(0, 1, 5e-2)[:, None]
print(pre_test_1.shape)
pre_test_2 = pre_test_1.reshape(10,2)
print(pre_test_2.shape)
pre_test_3 = pre_test_2.dot(2)
print(pre_test_3.shape)
pre_test_4 = np.matmul(pre_test_2, pre_test_3.T)
print(pre_test_4, pre_test_4.shape)

(20, 1)
(10, 2)
(10, 2)
[[0.005 0.015 0.025 0.035 0.045 0.055 0.065 0.075 0.085 0.095]
 [0.015 0.065 0.115 0.165 0.215 0.265 0.315 0.365 0.415 0.465]
 [0.025 0.115 0.205 0.295 0.385 0.475 0.565 0.655 0.745 0.835]
 [0.035 0.165 0.295 0.425 0.555 0.685 0.815 0.945 1.075 1.205]
 [0.045 0.215 0.385 0.555 0.725 0.895 1.065 1.235 1.405 1.575]
 [0.055 0.265 0.475 0.685 0.895 1.105 1.315 1.525 1.735 1.945]
 [0.065 0.315 0.565 0.815 1.065 1.315 1.565 1.815 2.065 2.315]
 [0.075 0.365 0.655 0.945 1.235 1.525 1.815 2.105 2.395 2.685]
 [0.085 0.415 0.745 1.075 1.405 1.735 2.065 2.395 2.725 3.055]
 [0.095 0.465 0.835 1.205 1.575 1.945 2.315 2.685 3.055 3.425]] (10, 10)


In [35]:
mm_mean = pre_test_4.mean(axis=0)
print(mm_mean)
mm_median = np.median(pre_test_4, axis=0)
print(mm_median)
print(pre_test_4.std(axis=0), pre_test_4.var(axis=0))

[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.02872281 0.14361407 0.25850532 0.37339657 0.48828782 0.60317908
 0.71807033 0.83296158 0.94785284 1.06274409] [8.250000e-04 2.062500e-02 6.682500e-02 1.394250e-01 2.384250e-01
 3.638250e-01 5.156250e-01 6.938250e-01 8.984250e-01 1.129425e+00]


In [78]:
rand_int = np.random.randint(1, 10, size=(3,2))
print(rand_int)
rand_uniform = np.random.uniform(size=(3,2))
print(rand_uniform)
rand_normal = np.random.normal(1, 5, size=(3,2))
print(rand_normal)

[[9 6]
 [3 7]
 [2 6]]
[[0.74235771 0.32312984]
 [0.1704043  0.46273633]
 [0.14615887 0.67988835]]
[[ 7.4768554   7.91381242]
 [ 2.56402993 -1.17446226]
 [-2.4571494  -1.5634193 ]]
