In [2]:
!pip install numpy

In [7]:
# !pip list
!pip --version

pip 20.2.2 from D:\Python\anaconda3\lib\site-packages\pip (python 3.8)



In [10]:
import numpy as np

In [35]:
def array_numpy():
    a = np.array([
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ])
    print(a)
    print(a[-1][-1])
    "Type data of array"
    print("Type Data :", a.dtype)
    "Shape of array"
    print("Shape :", a.shape)
    "Dimensi of array"
    print("Dimensi :", a.ndim)
array_numpy()

[[1 2 3 4]
 [5 6 7 8]]
8
Type Data : int32
Shape : (2, 4)
Dimensi : 2


In [42]:
def array_of_zeros():
    print(np.array(10))
    print("!--!")
    print(np.zeros(10))
array_of_zeros()

10
!--!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
def array_of_ones():
    print(np.ones(10))
array_of_ones()

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
def array_of_empty():
    print(np.empty((100, 100)))
array_of_empty()

[[7.42972961e-312 7.42973729e-312 3.49012913e-319 ... 5.30973833e+180
  6.23102918e+228 6.02669591e+175]
 [1.77942356e+248 9.08366791e+223 1.07031539e-013 ... 2.18953536e+068
  3.03426193e-086 1.81786144e+185]
 [6.68159286e+151 9.47212685e-154 2.16401696e-027 ... 2.54723493e+151
  1.97641705e+166 3.18489929e-114]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]


In [64]:
def array_of_arange():
    "start,stop,stop"
    print(np.arange(0, 100, 2))
array_of_arange()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [87]:
def array_of_array():
    arr_1 = np.array([["Ahmad", "Verry", "Setiawan"]])
    arr_2 = np.array([[17, 11, 94]])
    print(arr_1)
    "Append"
    print(arr_1.shape, arr_2.shape)
    print(np.append(arr_1, 17))
    print(np.append(arr_1, arr_2, axis=0))
array_of_array()

[['Ahmad' 'Verry' 'Setiawan']]
(1, 3) (1, 3)
['Ahmad' 'Verry' 'Setiawan' '17']
[['Ahmad' 'Verry' 'Setiawan']
 ['17' '11' '94']]


In [85]:
def array_of_delete():
    arr_1 = np.array(["Ahmad", "Verry", "Setiawan"])
    arr_2 = np.array([17, 11, 94])
    "Delete"
    array_append = np.append(arr_1, arr_2, axis=0)
    print(array_append)
    print("----------")
    print(np.delete(array_append, 0, axis=0))
array_of_delete()

['Ahmad' 'Verry' 'Setiawan' '17' '11' '94']
----------
['Verry' 'Setiawan' '17' '11' '94']


In [116]:
arr1 = np.array([[
    [10,98,54],
    [76,2,46],
    [24,36,92]
],[
    [45,63,82],
    [11,2,57],
    [54,19,45]
]])
arr2 = np.array([[
    [1,2,3],
    [76,2,46],
    [43,92,92]
]])
print(arr1.shape)
print('!----!')
print(arr1[(arr1 >= 82) & (arr1 > 92)])
print('!----!')
print(np.concatenate((arr1, arr2)))
print('!----!')
print(arr1.sum())
print('!----!')
print(arr1.std())

(2, 3, 3)
!----!
[98]
!----!
[[[10 98 54]
  [76  2 46]
  [24 36 92]]

 [[45 63 82]
  [11  2 57]
  [54 19 45]]

 [[ 1  2  3]
  [76  2 46]
  [43 92 92]]]
!----!
816
!----!
29.11089906623367
